added cypress-react-selector plugin and refactored athena reports tests
concord-consortium/integration-tests pull request #31
Opened 2021-08-05 19:17 UTC by sri-tscube

2021-08-06 17:58 UTC, tejal-shah commented on cypress/support/testdata/testdata_athena_reports.js
> +            teachers: ['Tejal Admin'],
Its probably fine for the purposes of this PR, but we should plan to have a cautomationteacher10 or 11 user that has a more comprehensive test data for testing Athena reports; Something that covers:
- various interactives - unreportable, managed, generic
- runtimes - lara runtime vs activity player
- single vs multiple teachers in a class, 
- individual students vs working with collaborators,
- single vs multiple classes for the same student, 
- activity vs sequence, 
- different states of question interactives like answered and submitted, saved but not submitted, not attempted but ran the activity, not ran the activity

2021-08-06 18:02 UTC, tejal-shah approved these changes

2021-08-06 21:15 UTC, scytacki requested changes
Overall looks good.

I just found one misspelling.
And one place where a hardcode string should be a variable.

2021-08-06 21:15 UTC, scytacki commented on cypress/support/helpers/athenaReportHelper.js
> +        downloadReport(expectedOutputRile);
```suggestion
        downloadReport(expectedOutputRule);
```

2021-08-06 21:15 UTC, scytacki commented on cypress/support/helpers/athenaReportHelper.js
> +    let learnerReportUrl = 'https://learn-report.staging.concord.org' + props.queryUrl;
the learner-report.staging.concord.org should be a variable since it will be different depending on which portal host you are testing against.

2021-08-06 21:15 UTC, scytacki commented on cypress/support/helpers/athenaReportHelper.js
> +function invokeReportUrl(queryUrlResp, reportUrl, expectedOutputRile){
```suggestion
function invokeReportUrl(queryUrlResp, reportUrl, expectedOutputRule){
```

2021-08-09 18:04 UTC, scytacki approved these changes
Looks good to me.

2021-08-09 19:46 UTC, merged