updated student activity test with feedback
concord-consortium/integration-tests pull request #7
Opened 2021-06-16 15:36 UTC by sri-tscube

added teacher feedback for activity and then student verifying the feedback.
Also made the tests depend on test data so that we can easily write tests for next activity

2021-06-16 21:11 UTC, scytacki approved these changes
looks good to me

2021-06-16 23:11 UTC, tejal-shah requested changes

2021-06-16 23:11 UTC, tejal-shah commented on cypress/support/elements/register_add_student_page_elements.js
> +  LBL_SIGNUP_SUCCESS: 'div.signup-form div.registration-complete.student div p',
These page elements seem to be from the signup page for the student. Can we please move them to the signup_page_elements.js? This file represents page elements within the teacher account within a class when the teacher registers and adds students directly to the class. I agree the name for this file is confusing, we should probably change it to something like teacher_register_add_student_page-elements.js

2021-06-17 13:52 UTC, tejal-shah approved these changes

2021-06-17 13:52 UTC, merged